### ISSUE TITLE
Help needed for preprocessing

### ISSUE THREAD

**Issue by davidsonic** [uci-cbcl/NoduleNet#14]
It seems that there're some problems running python cvrt_annos_to_npy.py. 

![image](https://user-images.githubusercontent.com/15846113/74771436-00ec6400-5243-11ea-8c52-0877e9edf0c6.png)

Not sure what the error indicates. Although the progress bars finishes, there were no files generated for further processing (process.py).

**Comment by berceanbogdan** [comment]
@davidsonic did you figure it out?

**Comment by LXYTSOS** [comment]
did you fix it?

**Comment by LXYTSOS** [comment]
don't use try catch block and you will see the error, and you can solve this in half an hour.
![QTOOUR5VIT UV$A)PUNJVA4](https://user-images.githubusercontent.com/8330006/85494994-48796700-b60c-11ea-9310-c1e92071bfc7.png)

**Comment by Webber-MP** [comment]
I encounter the same problem. Can you provide the solution how you solve it? Thank you!

**Comment by DongChen06** [comment]
@LXYTSOS @Webber-MP  any solutions for this problem?

**Comment by RonDen** [comment]
I encounter the same problem. Is there any solution?
It sames almost 20% .xml files (example: 186/089.xml) are CXRreadingSession, and namespace is not nih, but 'www.nih.gov/idri'
, so the xml element tree parse cannot find the right element in the namespace.

The CXRreadingSession miss many infomation in node characters. So I don't know how to fix this. It seems this problem came from the data annotations. Maybe, the XML file have been updated....
